services:
    dev-db:
        image: postgres:16
        ports:
            - '5434:5432'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: rentals
        networks:
            - backend
    test-db:
        image: postgres:16
        ports:
            - '5435:5432'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: rentals
        networks:
            - backend
networks:
    backend: {}
